import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar_design/navBar";
import { CartProvider } from "./selectitemCont";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <CartProvider>
      <body className={`${inter.className} space-y-6`}>
      
      <nav  className="sticky top-0">
        <Navbar/>
      </nav>
        {children}
        
      </body>
      </CartProvider>
    </html>
  );
}
